-- ==============================================================================
-- Coffee Adda (Budhanilkantha) - Supabase Cloud Database Schema & Initial Data
-- Run this script in the Supabase SQL Editor:
-- https://supabase.com/dashboard/project/ovuidldhzajdtfrcveng/sql/new
-- ==============================================================================

-- 1. CREATE MENU_ITEMS TABLE
CREATE TABLE IF NOT EXISTS public.menu_items (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    sub_category TEXT DEFAULT '',
    price INTEGER NOT NULL DEFAULT 0,
    tag TEXT DEFAULT '',
    dietary TEXT DEFAULT 'veg',
    description TEXT DEFAULT '',
    details JSONB DEFAULT '[]'::jsonb,
    image TEXT DEFAULT '',
    alt TEXT DEFAULT '',
    is_available BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;

-- Allow public read access to all menu items
DROP POLICY IF EXISTS "Public menu items read access" ON public.menu_items;
CREATE POLICY "Public menu items read access"
    ON public.menu_items FOR SELECT
    USING (true);

-- Allow public write access (for Staff Admin management)
DROP POLICY IF EXISTS "Public menu items insert access" ON public.menu_items;
CREATE POLICY "Public menu items insert access"
    ON public.menu_items FOR INSERT
    WITH CHECK (true);

DROP POLICY IF EXISTS "Public menu items update access" ON public.menu_items;
CREATE POLICY "Public menu items update access"
    ON public.menu_items FOR UPDATE
    USING (true)
    WITH CHECK (true);

DROP POLICY IF EXISTS "Public menu items delete access" ON public.menu_items;
CREATE POLICY "Public menu items delete access"
    ON public.menu_items FOR DELETE
    USING (true);

-- 2. CREATE REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGSERIAL PRIMARY KEY,
    author TEXT NOT NULL,
    role TEXT DEFAULT 'Guest',
    rating INTEGER DEFAULT 5,
    quote TEXT NOT NULL,
    initials TEXT DEFAULT '',
    avatar_bg TEXT DEFAULT 'bg-brand-sage text-brand-forest',
    is_approved BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public reviews read access" ON public.reviews;
CREATE POLICY "Public reviews read access"
    ON public.reviews FOR SELECT
    USING (is_approved = true);

DROP POLICY IF EXISTS "Public reviews insert access" ON public.reviews;
CREATE POLICY "Public reviews insert access"
    ON public.reviews FOR INSERT
    WITH CHECK (true);

-- 3. SEED 163 AUTHENTIC MENU ITEMS
INSERT INTO public.menu_items (id, name, category, sub_category, price, tag, dietary, description, details, image, alt, is_available) VALUES
('item-1', 'Cappuccino', 'hot', 'Espresso Bar', 280, 'Popular', 'non-veg', 'Rich, balanced double espresso topped with equal parts velvety steamed milk and airy foam with signature free-pour latte art.', '["\ud83e\udd5b Whole / Oat Milk", "\ud83d\udd25 Hot (8oz)"]'::jsonb, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBMjTB-ditOYgxnlYcLY6V54j2iwNiXT1m2XqIew3Bkse2f-SZYiDFV-55N0Et_85yx-V4H22ZM_cPsw8ly8xP-9k3h7gD4LBH6sdAZPstftH2YNWoQcEz3o8r_jyvunOGXrq99_KEHJGzpwC47b1j3IQtTlsJgr7beMTWxLmM8tGpzlK6jzSf7MhyxwYluZO13U_z_-G_A9O1I7ZbGUEbPi1iDi2OYysiTSYK92b117sjC-bO6nXih', 'Cappuccino', true),
('item-2', 'Caffè Latte', 'hot', 'Silky Smooth', 310, 'Barista Pick', 'non-veg', 'Gentle espresso combined with generous silky textured micro-foam milk in a sage ceramic cup. Mellow, sweet, and comforting.', '["\ud83e\udd5b Customizable", "\ud83d\udd25 Hot (10oz)"]'::jsonb, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-HydCGjJv_Tr3FhQJ-oXJCh5HT86JQnendHcw2JskFuZGYpXrv_flzBcfbWlH6zpOiIQ8GVrdVtOfZowkSqUtb-XUnOoJs_TRYLs54sZq5lvQ5FexFPcfP15FlUVcc39910_k9wJR6g54EsWJ7u_QaRy1XQxnW1TTBCi8zLh9-K6C1Tbrewg0vkMYqxL8vjmDGvlTQWE3g-docRIf5-duA2vbweeJYjTo-Q8e_Lky7XCmqM_lIrVG', 'Caffè Latte', true),
('item-3', 'Signature Iced Coffee', 'cold', 'Chilled', 340, 'Summer Fav', 'non-veg', 'Slow-drip 14-hour cold brew layered over condensed milk swirl, served tall on crystal cubes with whole roasted coffee bean garnish.', '["\ud83e\uddca Extra Chilled", "\u26a1 High Caffeine"]'::jsonb, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDNjPKlqKtESQ0TETpEvAJ6w_PSCQk9WgAA1Jgc4uHzJoZ09hVO10rICprzoG_ZB8gMYCO23wsuw-CQV0X0VvgsdhD3Y5eCXnqJGkFbUj2EZ4nLeyMkKTkPZnm92CqElBheeuEToElHeY9b_110tlgan7d383KkzKtSMQTFxQbL1heAHP0ZZ0M4-u3hl2cdUpx7-OUCjgjAi3OT0QSz4-fRL6cH04idkadg3soDM8gnkUMfW_UD4cSA', 'Signature Iced Coffee', true),
('item-4', 'Artisan Butter Croissant', 'bakery', 'Pastry', 220, 'Fresh Baked', 'non-veg', 'Flaky, multi-layered golden French pastry baked fresh daily at 6:30 AM with creamy alpine butter.', '["\ud83e\udd50 Hand-rolled", "\u2728 Warm Served"]'::jsonb, 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80', 'Artisan Butter Croissant', true),
('item-5', 'Cascara Sparkling Cold Brew', 'cold', 'Refresher', 330, 'Specialty', 'non-veg', 'Infused with organic coffee cherry peel, tonic water, and a twist of local fresh lime over crystal ice.', '["\ud83c\udf4b Citrus Zest", "\ud83e\uddca Light Fizz"]'::jsonb, 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80', 'Cascara Sparkling Cold Brew', true),
('item-6', 'Chocolate Babka Brioche', 'bakery', 'House Special', 260, 'Sweet Treat', 'non-veg', 'Braided sweet yeast bread swirled with 70% dark Himalayan cocoa and fragrant Ceylon cinnamon syrup.', '["\ud83c\udf6b Dark Chocolate", "\ud83c\udf6f Honey Glaze"]'::jsonb, 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80', 'Chocolate Babka Brioche', true),
('item-7', 'Espresso', 'hot-beverages', 'Espresso Bar', 110, 'Classic', 'non-veg', 'Concentrated single shot pulled with golden hazelnut crema from shade-grown high-altitude Arabica beans.', '["Pure Arabica", "Hot (1.5oz)"]'::jsonb, 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&w=600&q=80', 'Espresso', true),
('item-8', 'Doppio', 'hot-beverages', 'Espresso Bar', 130, 'Double Shot', 'non-veg', 'Bold double shot of concentrated espresso offering intense aroma and deep dark cocoa tasting notes.', '["Double Shot", "High Caffeine"]'::jsonb, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80', 'Doppio', true),
('item-9', 'Americano Single Shot', 'hot-beverages', 'Black Coffee', 130, 'Smooth', 'non-veg', 'Classic single shot espresso lengthened with hot mountain water for a clean, aromatic finish.', '["Hot Water Dilution", "Hot (8oz)"]'::jsonb, 'https://images.unsplash.com/photo-1551030173-122aabc4489c?auto=format&fit=crop&w=600&q=80', 'Americano Single Shot', true),
('item-10', 'Americano Double Shot', 'hot-beverages', 'Black Coffee', 160, 'Strong', 'non-veg', 'Intense double espresso pulled over hot water for the caffeine purist seeking deep roasted flavor.', '["Double Shot", "Hot (10oz)"]'::jsonb, 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=600&q=80', 'Americano Double Shot', true),
('item-11', 'Café Latte', 'hot-beverages', 'Milky & Smooth', 180, 'Barista Pick', 'non-veg', 'Gentle espresso harmonized with generous silky micro-foam in our signature sage ceramic mug.', '["Silky Micro-foam", "Hot (10oz)"]'::jsonb, 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-HydCGjJv_Tr3FhQJ-oXJCh5HT86JQnendHcw2JskFuZGYpXrv_flzBcfbWlH6zpOiIQ8GVrdVtOfZowkSqUtb-XUnOoJs_TRYLs54sZq5lvQ5FexFPcfP15FlUVcc39910_k9wJR6g54EsWJ7u_QaRy1XQxnW1TTBCi8zLh9-K6C1Tbrewg0vkMYqxL8vjmDGvlTQWE3g-docRIf5-duA2vbweeJYjTo-Q8e_Lky7XCmqM_lIrVG', 'Café Latte', true),
('item-12', 'Cappuccino / Double', 'hot-beverages', 'Espresso Bar', 180, 'Popular', 'non-veg', 'Rich, balanced espresso crowned with equal parts textured milk and velvety airy foam with rosetta art.', '["Dense Froth", "Hot (8oz)"]'::jsonb, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBMjTB-ditOYgxnlYcLY6V54j2iwNiXT1m2XqIew3Bkse2f-SZYiDFV-55N0Et_85yx-V4H22ZM_cPsw8ly8xP-9k3h7gD4LBH6sdAZPstftH2YNWoQcEz3o8r_jyvunOGXrq99_KEHJGzpwC47b1j3IQtTlsJgr7beMTWxLmM8tGpzlK6jzSf7MhyxwYluZO13U_z_-G_A9O1I7ZbGUEbPi1iDi2OYysiTSYK92b117sjC-bO6nXih', 'Cappuccino / Double', true),
('item-13', 'Café Mocha', 'hot-beverages', 'Chocolate Espresso', 210, 'Indulgent', 'non-veg', 'Double espresso blended with molten dark chocolate, steamed milk, and light cocoa dusting.', '["Dark Chocolate", "Hot (8oz)"]'::jsonb, 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=600&q=80', 'Café Mocha', true),
('item-14', 'Honey Latte', 'hot-beverages', 'Naturally Sweet', 220, 'House Special', 'non-veg', 'Smooth espresso and steamed milk sweetened with natural wild Himalayan blossom honey.', '["Pure Honey", "Hot (10oz)"]'::jsonb, 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&w=600&q=80', 'Honey Latte', true),
('item-15', 'Caramel Macchiato', 'hot-beverages', 'Layered Caramel', 270, 'Sweet Fav', 'non-veg', 'Freshly steamed milk marked with vanilla syrup, rich espresso, and buttery golden caramel drizzle.', '["Buttery Caramel", "Hot (10oz)"]'::jsonb, 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=600&q=80', 'Caramel Macchiato', true),
('item-16', 'Mocha Madness', 'hot-beverages', 'Signature Dessert', 350, 'Chef Special', 'non-veg', 'Decadent specialty creation loaded with rich fudge, espresso, steamed cream, and dark cocoa shavings.', '["Fudge Loaded", "Signature Dessert"]'::jsonb, 'https://images.unsplash.com/photo-1579888944880-d98341245702?auto=format&fit=crop&w=600&q=80', 'Mocha Madness', true),
('item-17', 'Black Tea', 'tea-special', 'Orthodox Teas', 50, 'Pure Mountain Leaf', 'non-veg', 'Crisp and golden amber liquor brewed from handpicked high-altitude orthodox tea leaves from Eastern Nepal.', '["Handpicked Leaf", "Steaming Hot"]'::jsonb, 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80', 'Black Tea', true),
('item-18', 'Lemon Tea', 'tea-special', 'Citrus Infusions', 70, 'Zesty & Fresh', 'non-veg', 'Fragrant black tea brightened with freshly squeezed mountain lemon juice for an invigorating citrus finish.', '["Fresh Lemon Slice", "Uplifting Sips"]'::jsonb, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80', 'Lemon Tea', true),
('item-19', 'Milk Tea (Dudh Chiya)', 'tea-special', 'Traditional Chiya', 70, 'Everyday Classic', 'non-veg', 'The soul of Nepali morning addas  -  rich black tea simmered gently with whole fresh milk and sugar.', '["Fresh Simmered Milk", "Authentic Dudh Chiya"]'::jsonb, 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80', 'Milk Tea (Dudh Chiya)', true),
('item-20', 'Black Masala Tea', 'tea-special', 'Ayurvedic Spices', 100, 'Warming Spices', 'non-veg', 'Brisk black tea boiled with crushed green cardamom, cinnamon quills, cloves, and fiery ginger root.', '["Whole Spices", "Warming Decoction"]'::jsonb, 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=600&q=80', 'Black Masala Tea', true),
('item-21', 'Milk Masala Tea', 'tea-special', 'Traditional Chiya', 120, 'House Favorite', 'non-veg', 'Our house signature spiced milk tea decoction simmered with mountain cardamom, cloves, ginger, and fresh milk.', '["Spiced Dairy Brew", "House Blend"]'::jsonb, 'https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?auto=format&fit=crop&w=600&q=80', 'Milk Masala Tea', true),
('item-22', 'Matka Tea (Clay Pot)', 'tea-special', 'Clay Pot Special', 120, 'Rustic Clay Kulhad', 'non-veg', 'Aromatic spiced milk tea served in an authentic earthen terracotta clay pot (kulhad/matka) for an earthy smoky aroma.', '["Terracotta Clay Cup", "Earthy Smoky Note"]'::jsonb, 'https://images.unsplash.com/photo-1571934811356-5cc061b6821f?auto=format&fit=crop&w=600&q=80', 'Matka Tea (Clay Pot)', true),
('item-23', 'Chocolate Tea', 'tea-special', 'Dessert Teas', 140, 'Choco Delight', 'non-veg', 'Rich fusion of robust milk tea simmered with molten Dutch dark cocoa and topped with chocolate shavings.', '["Dark Dutch Cocoa", "Creamy Dessert Sip"]'::jsonb, 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=600&q=80', 'Chocolate Tea', true),
('item-24', 'Green Tea', 'tea-special', 'Antioxidant Greens', 80, 'Wellness & Detox', 'non-veg', 'Steamed whole green tea leaves from Ilam mountain gardens, offering gentle vegetal sweetness and light finish.', '["100% Whole Leaf", "Clean Detox"]'::jsonb, 'https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?auto=format&fit=crop&w=600&q=80', 'Green Tea', true),
('item-25', 'Green Tea with Lemon', 'tea-special', 'Antioxidant Greens', 100, 'Citrus Detox', 'non-veg', 'Pure Ilam green tea infused with freshly cut mountain lemon slices for an energizing antioxidant-rich cup.', '["Fresh Cut Lemon", "Immunity Boost"]'::jsonb, 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80', 'Green Tea with Lemon', true),
('item-26', 'Hot Lemon', 'tea-special', 'Warm Herbal Drinks', 80, 'Throat Soother', 'non-veg', 'Steaming cup of freshly squeezed lemon juice steeped in hot water to soothe the throat and refresh the senses.', '["100% Real Citrus", "Steaming Hot"]'::jsonb, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', 'Hot Lemon', true),
('item-27', 'Hot Lemon with Honey', 'tea-special', 'Warm Herbal Drinks', 150, 'Immunity Boost', 'non-veg', 'Golden wild forest honey stirred with fresh tart mountain lemon juice into steaming hot mountain spring water.', '["Pure Wild Honey", "Fresh Tart Lemon"]'::jsonb, 'https://images.unsplash.com/photo-1546852199-2d8e8c4aaada?auto=format&fit=crop&w=600&q=80', 'Hot Lemon with Honey', true),
('item-28', 'Hot Lemon with Ginger Honey', 'tea-special', 'Warm Herbal Drinks', 170, 'Winter Classic', 'non-veg', 'Freshly crushed pungent ginger root simmered with natural mountain honey and fresh lemon juice. Highly recommended for cool Budhanilkantha mornings.', '["\ud83e\udeda Crushed Ginger", "Mountain Honey", "Tart Lemon"]'::jsonb, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', 'Hot Lemon with Ginger Honey', true),
('item-29', 'Rose Tea', 'tea-special', 'Floral Infusions', 120, 'Calming Floral', 'non-veg', 'Dried fragrant organic rose petals steeped gently for a delicate floral aroma and calming subtle sweetness.', '["Dried Rose Petals", "Calming Aromatics"]'::jsonb, 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=600&q=80', 'Rose Tea', true),
('item-30', 'Peach Tea', 'tea-special', 'Fruity Infusions', 100, 'Fruity Delight', 'non-veg', 'Sweet juicy peach fruit essence infused into gentle steeped tea leaves, bursting with fruity aroma.', '["Juicy Peach", "Refreshing Sips"]'::jsonb, 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80', 'Peach Tea', true),
('item-31', 'Expresso on the Rock', 'cold-beverages', 'Chilled Espresso', 140, 'Crisp', 'non-veg', 'Fresh double espresso pulled directly over hand-cut crystal clear ice cubes for instant cooling.', '["On The Rocks", "Strong & Crisp"]'::jsonb, 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80', 'Expresso on the Rock', true),
('item-32', 'Iced Americano', 'cold-beverages', 'Chilled Black', 170, 'Refreshing', 'non-veg', 'Cold mountain spring water mixed with bold espresso and poured over mountain ice cubes.', '["Cold Water Brew", "Zero Sugar"]'::jsonb, 'https://images.unsplash.com/photo-1551030173-122aabc4489c?auto=format&fit=crop&w=600&q=80', 'Iced Americano', true),
('item-33', 'Iced Latte', 'cold-beverages', 'Chilled Milk Brew', 200, 'All-Day Fav', 'non-veg', 'Fresh espresso poured gently over cold whole milk and ice, creating smooth coffee-milk layers.', '["Creamy Layers", "Tall Glass"]'::jsonb, 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=600&q=80', 'Iced Latte', true),
('item-34', 'Iced Cappuccino', 'cold-beverages', 'Cold Foam', 200, 'Frothy', 'non-veg', 'Chilled espresso and milk crowned with a thick velvety layer of cold aerated milk foam.', '["Cold Micro-foam", "Crisp Chill"]'::jsonb, 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=600&q=80', 'Iced Cappuccino', true),
('item-35', 'Iced Mocha', 'cold-beverages', 'Chocolate Chill', 220, 'Popular', 'non-veg', 'Rich dark chocolate and cold espresso combined over ice with fresh milk and chocolate swirl.', '["Dark Chocolate", "Cold & Rich"]'::jsonb, 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80', 'Iced Mocha', true),
('item-36', 'Iced Caramel Macchiato', 'cold-beverages', 'Layered Chill', 310, 'Summer Fav', 'non-veg', 'Chilled vanilla milk marked with espresso shot and generous golden buttery caramel drizzle.', '["Salted Caramel", "High Energy"]'::jsonb, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDNjPKlqKtESQ0TETpEvAJ6w_PSCQk9WgAA1Jgc4uHzJoZ09hVO10rICprzoG_ZB8gMYCO23wsuw-CQV0X0VvgsdhD3Y5eCXnqJGkFbUj2EZ4nLeyMkKTkPZnm92CqElBheeuEToElHeY9b_110tlgan7d383KkzKtSMQTFxQbL1heAHP0ZZ0M4-u3hl2cdUpx7-OUCjgjAi3OT0QSz4-fRL6cH04idkadg3soDM8gnkUMfW_UD4cSA', 'Iced Caramel Macchiato', true),
('item-37', 'Iced Mocha Madness', 'cold-beverages', 'Signature Shake', 360, 'Ultimate Treat', 'non-veg', 'Our show-stopping iced creation with double espresso, blended chocolate fudge, whipped cream and cocoa.', '["Loaded Fudge", "House Signature"]'::jsonb, 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80', 'Iced Mocha Madness', true),
('item-38', 'Classic Mojito', 'shakes-lassi', 'Virgin Mojito', 210, 'Refreshing', 'non-veg', 'Fresh mountain garden mint leaves muddled with lime wedges, cane sugar syrup, and fizzy soda over ice.', '["Fresh Mint", "Lime & Soda"]'::jsonb, 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', 'Classic Mojito', true),
('item-39', 'Fruit Crush Mojito', 'shakes-lassi', 'Specialty Mojito', 285, 'Signature Chill', 'non-veg', 'Crushed seasonal fresh fruits, muddled fresh mint, citrus juice and sparkling soda poured over ice.', '["Crushed Fruits", "Muddled Mint"]'::jsonb, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', 'Fruit Crush Mojito', true),
('item-40', 'Hot Chocolate', 'shakes-lassi', 'Warm Comfort', 200, 'Comforting', 'non-veg', 'Velvety melted dark cocoa simmered with fresh whole milk and a hint of vanilla warmth.', '["Pure Cocoa", "Hot Mug"]'::jsonb, 'https://images.unsplash.com/photo-1542990253-0d0f5be5f0ed?auto=format&fit=crop&w=600&q=80', 'Hot Chocolate', true),
('item-41', 'Milk Shake (Choc / Van / Straw)', 'shakes-lassi', 'Classic Shake', 250, 'Creamy Classic', 'non-veg', 'Thick, creamy milkshake blended with premium dairy ice cream in your choice of Chocolate, Vanilla, or Strawberry.', '["Ice Cream Blended", "3 Flavor Choices"]'::jsonb, 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80', 'Milk Shake (Choc / Van / Straw)', true),
('item-42', 'Blended Oreo Shake', 'shakes-lassi', 'Oreo Shake', 295, 'Top Favorite', 'non-veg', 'Crisp Oreo cookies crushed and blended with rich vanilla ice cream, whole milk, and dark chocolate drizzle.', '["Real Oreo Cookies", "Chocolate Swirl"]'::jsonb, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80', 'Blended Oreo Shake', true),
('item-43', 'Oreo Shake', 'shakes-lassi', 'Classic Shake', 280, 'Popular', 'non-veg', 'Rich creamy vanilla shake infused with crunchy chocolate Oreo cookie crumbles.', '["Oreo Bits", "Rich Cream"]'::jsonb, 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80', 'Oreo Shake', true),
('item-44', 'Kitkat Shake', 'shakes-lassi', 'Candy Shake', 240, 'Chocolate Crunch', 'non-veg', 'Crispy KitKat wafer bars blended with velvety ice cream and chocolate sauce.', '["KitKat Bars", "Wafer Crunch"]'::jsonb, 'https://images.unsplash.com/photo-1579888944880-d98341245702?auto=format&fit=crop&w=600&q=80', 'Kitkat Shake', true),
('item-45', 'Blueberry Milk Shake', 'shakes-lassi', 'Berry Shake', 280, 'Fruity Delight', 'non-veg', 'Wild blueberries blended smoothly with vanilla ice cream and whole milk for a rich berry treat.', '["\ud83e\uded0 Real Blueberries", "Creamy Blend"]'::jsonb, 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80', 'Blueberry Milk Shake', true),
('item-46', 'Mint Lemonade', 'shakes-lassi', 'Citrus Cooler', 190, 'Zesty Refresher', 'non-veg', 'Freshly squeezed lemon juice, muddled wild mint, cane syrup, and chilled soda water.', '["Fresh Lemons", "Garden Mint"]'::jsonb, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', 'Mint Lemonade', true),
('item-47', 'Ice Tea (Peach & Lemon)', 'shakes-lassi', 'Iced Tea', 180, 'Cool Brew', 'non-veg', 'Slow-steeped Himalayan black tea served cold over ice with natural sweet peach and freshly squeezed lemon.', '["Peach Essence", "Fresh Lemon"]'::jsonb, 'https://images.unsplash.com/photo-1499638673689-79a0b5115d87?auto=format&fit=crop&w=600&q=80', 'Ice Tea (Peach & Lemon)', true),
('item-48', 'Masala Cold Drinks', 'shakes-lassi', 'Spiced Soda', 140, 'Nepali Zing', 'non-veg', 'Chilled soda spiked with roasted cumin, chaat masala, rock salt, and tangy fresh lemon juice.', '["Rock Salt & Cumin", "Lemon Zing"]'::jsonb, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', 'Masala Cold Drinks', true),
('item-49', 'Cranberry Juice', 'shakes-lassi', 'Fruit Juice', 130, 'Tart & Sweet', 'non-veg', 'Crisp, chilled red cranberry juice served tall with crystal ice.', '["Pure Cranberry", "Chilled Glass"]'::jsonb, 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80', 'Cranberry Juice', true),
('item-50', 'Cold Drinks (Coke / Fanta / Sprite)', 'shakes-lassi', 'Soft Drink', 100, 'Chilled Can', 'non-veg', 'Your choice of chilled Coke, Fanta, or Sprite served over ice cubes with lemon slice.', '["Choice of Soda", "Served Over Ice"]'::jsonb, 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=600&q=80', 'Cold Drinks (Coke / Fanta / Sprite)', true),
('item-51', 'Smoothies in Crunch Strawberry', 'shakes-lassi', 'Fruit Smoothie', 260, 'Crunchy', 'non-veg', 'Thick real strawberry fruit smoothie blended with crushed ice, topped with crispy crunchy pearls.', '["Real Strawberries", "Crunchy Topping"]'::jsonb, 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80', 'Smoothies in Crunch Strawberry', true),
('item-52', 'Smoothies in Crunch Mango', 'shakes-lassi', 'Fruit Smoothie', 260, 'Tropical', 'non-veg', 'Tropical ripe mango pulp blended rich and thick, finished with crunchy roasted granola crunch.', '["Sweet Mango", "Granola Crunch"]'::jsonb, 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80', 'Smoothies in Crunch Mango', true),
('item-53', 'Smoothies in Crunch Blueberry', 'shakes-lassi', 'Fruit Smoothie', 285, 'Antioxidant', 'non-veg', 'Lush dark blueberries blended with natural mountain yogurt, honey, and a crunch topping.', '["\ud83e\uded0 Wild Blueberry", "Mountain Yogurt"]'::jsonb, 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80', 'Smoothies in Crunch Blueberry', true),
('item-54', 'Smoothies in Seasonal Fruits', 'shakes-lassi', 'Fruit Smoothie', 365, 'Chef Deluxe', 'non-veg', 'Loaded deluxe smoothie crafted from a vibrant medley of fresh seasonal Himalayan fruits and honey.', '["Multi-fruit Blend", "Pure Honey"]'::jsonb, 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=600&q=80', 'Smoothies in Seasonal Fruits', true),
('item-55', 'Vanilla Frappe', 'shakes-lassi', 'Blended Coffee', 350, 'Smooth & Rich', 'non-veg', 'Iced espresso blended with Madagascar vanilla syrup, chilled milk, and whipped cream topping.', '["Espresso Blend", "French Vanilla"]'::jsonb, 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80', 'Vanilla Frappe', true),
('item-56', 'Hazelnut Frappe', 'shakes-lassi', 'Blended Coffee', 280, 'Nutty Note', 'non-veg', 'Roasted hazelnut syrup blended with chilled double espresso, milk, and crushed ice.', '["Roasted Hazelnut", "Double Espresso"]'::jsonb, 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=600&q=80', 'Hazelnut Frappe', true),
('item-57', 'Caramel Frappe', 'shakes-lassi', 'Blended Coffee', 290, 'Caramel Swirl', 'non-veg', 'Smooth coffee frappe blended with buttery caramel sauce and topped with golden caramel drizzle.', '["Golden Caramel", "Blended Cold"]'::jsonb, 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?auto=format&fit=crop&w=600&q=80', 'Caramel Frappe', true),
('item-58', 'Oreo Frappe', 'shakes-lassi', 'Blended Coffee', 300, 'Cookie Blend', 'non-veg', 'Blended iced coffee mixed with crunchy Oreo cookies and chocolate syrup drizzle.', '["Crushed Oreo", "Coffee Infused"]'::jsonb, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80', 'Oreo Frappe', true),
('item-59', 'Choco Mint Frappe', 'shakes-lassi', 'Blended Coffee', 320, 'Cooling', 'non-veg', 'A cooling combination of dark chocolate, refreshing garden mint, and chilled espresso.', '["Dark Chocolate", "Cooling Mint"]'::jsonb, 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&w=600&q=80', 'Choco Mint Frappe', true),
('item-60', 'Mocha Frappe', 'shakes-lassi', 'Blended Coffee', 360, 'Decadent', 'non-veg', 'Ice-blended espresso and Belgian chocolate with whipped cream and cocoa shavings.', '["Belgian Chocolate", "Double Espresso"]'::jsonb, 'https://images.unsplash.com/photo-1579888944880-d98341245702?auto=format&fit=crop&w=600&q=80', 'Mocha Frappe', true),
('item-61', 'Plain Lassi', 'shakes-lassi', 'Nepali Lassi', 150, 'Traditional', 'non-veg', 'Authentic curd churned traditional style with a pinch of roasted cumin and Himalayan salt.', '["Fresh Curd", "Refreshing"]'::jsonb, 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80', 'Plain Lassi', true),
('item-62', 'Sweet Lassi', 'shakes-lassi', 'Nepali Lassi', 170, 'Popular', 'non-veg', 'Traditional sweet yogurt beverage churned thick and chilled with aromatic green cardamom.', '["Thick Sweet Curd", "Green Cardamom"]'::jsonb, 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80', 'Sweet Lassi', true),
('item-63', 'Banana Lassi', 'shakes-lassi', 'Nepali Lassi', 190, 'Energy Booster', 'non-veg', 'Ripe bananas blended with thick mountain yogurt and natural honey for a wholesome treat.', '["Sweet Bananas", "Natural Honey"]'::jsonb, 'https://images.unsplash.com/photo-1528498033373-3c6c08e93d79?auto=format&fit=crop&w=600&q=80', 'Banana Lassi', true),
('item-64', 'Vanilla Lassi', 'shakes-lassi', 'Nepali Lassi', 180, 'Delicate', 'non-veg', 'Creamy churned yogurt flavored with pure vanilla extract and crushed ice.', '["Vanilla Scent", "Creamy Texture"]'::jsonb, 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80', 'Vanilla Lassi', true),
('item-65', 'Chocolate Lassi', 'shakes-lassi', 'Nepali Lassi', 200, 'Fusion Delight', 'non-veg', 'A delicious fusion of fresh mountain curd and molten chocolate fudge syrup.', '["Chocolate Fudge", "Fresh Curd"]'::jsonb, 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80', 'Chocolate Lassi', true),
('item-66', 'Strawberry Lassi', 'shakes-lassi', 'Nepali Lassi', 200, 'Berry Sweet', 'non-veg', 'Fresh local strawberries blended with rich mountain yogurt and served chilled.', '["Strawberry Puree", "Churned Curd"]'::jsonb, 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=600&q=80', 'Strawberry Lassi', true),
('item-67', 'Plain Toast (2 pcs)', 'breakfast', 'Toasts & Breads', 80, 'Crisp & Warm', 'non-veg', 'Two slices of freshly browned golden toasted artisan bread served warm and crisp.', '["2 Slices", "Warm & Crispy"]'::jsonb, 'https://images.unsplash.com/photo-1584776296944-ab6fb57b0bdd?auto=format&fit=crop&w=600&q=80', 'Plain Toast (2 pcs)', true),
('item-68', 'Butter Toast', 'breakfast', 'Toasts & Breads', 120, 'Morning Classic', 'non-veg', 'Golden toasted artisan bread slices generously slathered with rich melting dairy butter.', '["Creamy Dairy Butter", "2 Crisp Slices"]'::jsonb, 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80', 'Butter Toast', true),
('item-69', 'French Toast', 'breakfast', 'Sweet Breakfast', 150, 'Sweet Favorite', 'non-veg', 'Thick sliced bread dipped in a vanilla-cinnamon egg custard and griddled to golden caramel perfection.', '["Cinnamon & Honey", "Egg Custard Dipped"]'::jsonb, 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=600&q=80', 'French Toast', true),
('item-70', 'Plain Omelet', 'breakfast', 'Fresh Farm Eggs', 80, 'High Protein', 'non-veg', 'Light and fluffy two-egg pan-folded omelet lightly seasoned with rock salt and ground black pepper.', '["2 Farm Eggs", "Pan Folded Fluffy"]'::jsonb, 'https://images.unsplash.com/photo-1510693206972-df098062cb71?auto=format&fit=crop&w=600&q=80', 'Plain Omelet', true),
('item-71', 'Masala Omelet', 'breakfast', 'Fresh Farm Eggs', 120, 'Nepali Style', 'non-veg', 'Whipped double egg omelet loaded with finely chopped red onions, crisp green chilies, fresh coriander, and spices.', '["Green Chilly & Herbs", "2 Farm Eggs"]'::jsonb, 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=600&q=80', 'Masala Omelet', true),
('item-72', 'Sunny Side-Up', 'breakfast', 'Fresh Farm Eggs', 80, 'Runny Yolk', 'non-veg', 'Fresh skillet-fried farm egg with tender whites and delicate runny golden yolk, sprinkled with black pepper.', '["Runny Yolk", "Quick Protein"]'::jsonb, 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80', 'Sunny Side-Up', true),
('item-73', 'Boiled Eggs', 'breakfast', 'Fresh Farm Eggs', 80, 'Wholesome', 'non-veg', 'Two freshly boiled high-altitude farm eggs halved and served with Himalayan black salt and cracked pepper.', '["2 Boiled Eggs", "Himalayan Rock Salt"]'::jsonb, 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=600&q=80', 'Boiled Eggs', true),
('item-74', 'Fried Egg', 'breakfast', 'Fresh Farm Eggs', 80, 'Crispy Edges', 'non-veg', 'Sizzling pan-fried egg with crispy golden lacy edges, tender whites, and soft center.', '["Crispy Lacy Edges", "Sizzling Skillet"]'::jsonb, 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?auto=format&fit=crop&w=600&q=80', 'Fried Egg', true),
('item-75', 'Scrambled Egg', 'breakfast', 'Fresh Farm Eggs', 100, 'Velvety Soft', 'non-veg', 'Slow-cooked creamy scrambled eggs folded gently with fresh dairy butter and chives.', '["Butter Folded", "Silky & Soft"]'::jsonb, 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80', 'Scrambled Egg', true),
('item-76', 'Coffee Adda Special Breakfast Platter', 'breakfast', 'Grand Breakfast Combo', 650, 'Grand Feast', 'non-veg', 'The ultimate morning feast: Toasted artisan bread + choice of 2 savory sausages or bacon + 2 eggs (boiled or fried) + crispy garlic potatoes + dairy butter + sweet fruit jam + fresh seasonal fruit bowl.', '["Toast + Butter/Jam", "2 Eggs + 2 Sausages/Bacon", "Crispy Garlic Potato", "Seasonal Fruit Bowl"]'::jsonb, 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=600&q=80', 'Coffee Adda Special Breakfast Platter', true),
('item-77', 'Chicken Burger', 'burgers-sandwiches', 'Gourmet Burger', 290, 'Bestseller', 'non-veg', 'Juicy seasoned chicken patty grilled to perfection, melted cheddar cheese, crisp lettuce, tomato & house sauce.', '["Juicy Patty", "Cheddar Melt"]'::jsonb, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80', 'Chicken Burger', true),
('item-78', 'Egg Burger', 'burgers-sandwiches', 'Quick Burger', 250, 'Protein Rich', 'non-veg', 'Golden fried egg layered with caramelized onions, fresh garden greens, sliced tomatoes and tangy herb mayo.', '["Farm Fresh Egg", "Toasted Bun"]'::jsonb, 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80', 'Egg Burger', true),
('item-79', 'Veg Burger', 'burgers-sandwiches', 'Crispy Veg', 150, 'Budget Friendly', 'veg', 'Crispy spiced vegetable patty loaded with cucumber, tomato, fresh lettuce, and signature mayonnaise.', '["Crispy Veg Patty", "Garden Fresh"]'::jsonb, 'https://images.unsplash.com/photo-1520072959219-c595dc870360?auto=format&fit=crop&w=600&q=80', 'Veg Burger', true),
('item-80', 'Veg Cheese Sandwich', 'burgers-sandwiches', 'Toasted Sandwich', 180, 'Cheesy', 'veg', 'Golden toasted artisan bread filled with fresh vegetables, house butter, and rich melted mozzarella cheese.', '["Melted Mozzarella", "Grilled Crisp"]'::jsonb, 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80', 'Veg Cheese Sandwich', true),
('item-81', 'Chicken Sandwich', 'burgers-sandwiches', 'Toasted Sandwich', 210, 'Popular', 'non-veg', 'Tender spiced shredded chicken tossed with savory dressing, black pepper, and crisp lettuce in toasted bread.', '["Shredded Chicken", "Spiced Dressing"]'::jsonb, 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=600&q=80', 'Chicken Sandwich', true),
('item-82', 'Egg Sandwich', 'burgers-sandwiches', 'Toasted Sandwich', 200, 'Classic', 'non-veg', 'Fluffy farm-fresh egg omelette seasoned with Himalayan herbs, sandwiched inside warm toasted bread slices.', '["Farm Egg Omelette", "Warm Toasted"]'::jsonb, 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80', 'Egg Sandwich', true),
('item-83', 'Veg Mo:Mo Platter', 'momo-platters', '25 Pcs Feast', 600, 'Sharing Feast', 'veg', 'Grand 25 pcs tasting platter: 5 pcs Steamed + 5 pcs Fried + 5 pcs Sadheko + 5 pcs Kothey + 5 pcs Chilly Mo:Mo with spicy chutney.', '["25 Pieces Total", "5 Styles in One"]'::jsonb, 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?auto=format&fit=crop&w=600&q=80', 'Veg Mo:Mo Platter', true),
('item-84', 'Buff Mo:Mo Platter', 'momo-platters', '25 Pcs Feast', 640, 'Local Favorite', 'non-veg', 'Authentic 25 pcs buff extravaganza: 5 Steamed + 5 Deep Fried + 5 Pungent Sadheko + 5 Pan-fried Kothey + 5 Spicy Chilly Mo:Mo.', '["25 Pieces Buff", "Includes Sadheko & Chilly"]'::jsonb, 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=600&q=80', 'Buff Mo:Mo Platter', true),
('item-85', 'Chicken Mo:Mo Platter', 'momo-platters', '25 Pcs Feast', 660, 'Chef Signature', 'non-veg', 'The ultimate chicken lover feast: 5 Steamed + 5 Fried + 5 Tangy Sadheko + 5 Crispy Kothey + 5 Fiery Chilly Chicken Mo:Mo.', '["25 Pieces Chicken", "Perfect for Groups"]'::jsonb, 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80', 'Chicken Mo:Mo Platter', true),
('item-86', 'Current Platter', 'momo-platters', 'Spicy Combo', 420, 'Hot & Spicy', 'non-veg', '2 Packets of fiery Current Noodles wok-tossed and served with 2 Fried Eggs, 2 Savory Sausages, and fresh crisp garden salad.', '["2x Current Noodles", "2 Eggs + 2 Sausages"]'::jsonb, 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80', 'Current Platter', true),
('item-87', 'Spaghetti Carbonara', 'pasta-corndogs', 'Classic Italian Pasta', 500, 'House Premium', 'non-veg', 'Silky al dente spaghetti twirled in rich egg yolk cream sauce, aged parmesan cheese, cracked black peppercorns, and savory crispy bits.', '["Al Dente Spaghetti", "Aged Parmesan & Cream"]'::jsonb, 'https://images.unsplash.com/photo-1612874742237-6526221588e3?auto=format&fit=crop&w=600&q=80', 'Spaghetti Carbonara', true),
('item-88', 'Chicken Bolognese', 'pasta-corndogs', 'Slow Simmered Ragù', 420, 'Hearty Meat Sauce', 'non-veg', 'Slow-cooked minced chicken simmered in rich San Marzano tomato sauce with aromatic garlic, basil, and Italian oregano over pasta.', '["Minced Chicken Rag\u00f9", "Italian Herb Tomato"]'::jsonb, 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80', 'Chicken Bolognese', true),
('item-89', 'Arrabbiata', 'pasta-corndogs', 'Fiery Red Sauce', 350, 'Spicy & Zesty', 'non-veg', 'Tender pasta tossed in fiery red tomato sauce infused with toasted red chilies, garlic slivers, olive oil, and fresh basil leaves.', '["Spicy Red Chili", "Fresh Basil & Garlic"]'::jsonb, 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80', 'Arrabbiata', true),
('item-90', 'Pasta Alfredo', 'pasta-corndogs', 'Velvety White Sauce', 400, 'Rich & Creamy', 'non-veg', 'Decadent creamy white sauce made from fresh dairy cream, butter, and grated parmesan tossed with al dente pasta and herbs.', '["Dairy Cream & Butter", "Grated Parmesan"]'::jsonb, 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=600&q=80', 'Pasta Alfredo', true),
('item-91', 'Corn Dog (Classic Non-Veg / Veg)', 'pasta-corndogs', 'Street Corn Dog', 160, 'Crispy Skewer', 'veg', 'Juicy sausage or spiced filling dipped in sweet golden cornmeal batter, deep-fried until crisp and drizzled with mustard and ketchup.', '["Crispy Corn Crust", "Ketchup & Mustard Dip"]'::jsonb, 'https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=600&q=80', 'Corn Dog (Classic Non-Veg / Veg)', true),
('item-92', 'Cheese Corn Dog', 'pasta-corndogs', 'Molten Mozzarella', 180, 'Epic Cheese Pull', 'non-veg', 'Thick block of creamy mozzarella cheese enclosed in crunchy sweet cornmeal batter, fried golden with epic stretchy cheese pull.', '["Stretchy Mozzarella", "Crunchy Golden Crust"]'::jsonb, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80', 'Cheese Corn Dog', true),
('item-93', 'Plain Laphing (Jhol / Dry)', 'laphing', 'Tibetan Cold Jelly', 65, 'Street Classic', 'non-veg', 'Traditional silky cold mung bean jelly roll tossed in spicy Sichuan pepper oil, dark soy sauce, crushed garlic, and vinegar. Served in Jhol or Dry style.', '["Spicy Chili Oil", "Jhol or Dry Option"]'::jsonb, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80', 'Plain Laphing (Jhol / Dry)', true),
('item-94', 'Noodles Laphing (Jhol / Dry)', 'laphing', 'Stuffed Laphing', 75, 'Bestseller', 'non-veg', 'Silky yellow laphing sheets wrapped around seasoned chewy instant noodles, immersed in fiery garlic-chili vinegar sauce.', '["Noodle Stuffed", "Fiery Garlic Broth"]'::jsonb, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80', 'Noodles Laphing (Jhol / Dry)', true),
('item-95', 'Chips Laphing (Jhol / Dry)', 'laphing', 'Crunchy Fusion', 80, 'Crunchy Favorite', 'non-veg', 'Coffee Adda special twist: crisp spiced potato chips rolled snugly inside tender cold laphing with spicy tangy chili sauce.', '["Crunchy Spiced Chips", "Hot & Tangy"]'::jsonb, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80', 'Chips Laphing (Jhol / Dry)', true),
('item-96', 'Mix Laphing (Jhol / Dry)', 'laphing', 'Loaded Combination', 85, 'All-in-One', 'non-veg', 'The ultimate laphing bowl loaded with tender gluten jelly, noodles, and crunchy potato chips drenched in spicy Sichuan sauce.', '["Jelly + Noodles + Chips", "Extra Spicy"]'::jsonb, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80', 'Mix Laphing (Jhol / Dry)', true),
('item-97', 'Chicken Laphing (Jhol / Dry)', 'laphing', 'Savory Non-Veg', 130, 'Savory Special', 'non-veg', 'Tender spiced minced chicken tucked inside silky cold laphing sheets, dressed in chili-infused garlic vinegar and roasted sesame seeds.', '["Spiced Minced Chicken", "Jhol or Dry Option"]'::jsonb, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80', 'Chicken Laphing (Jhol / Dry)', true),
('item-98', 'Veg Khaja Set', 'khaja-mains', 'Traditional Nepali', 250, 'Authentic', 'veg', 'Crisp beaten rice (baji), roasted soybeans (bhatmas), spicy potato curry (aloo sadheko), fresh green salad and house pickles.', '["Beaten Rice", "Bhatmas & Aloo"]'::jsonb, 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80', 'Veg Khaja Set', true),
('item-99', 'Chicken Khaja Set', 'khaja-mains', 'Traditional Nepali', 280, 'Bestseller', 'non-veg', 'Nepali style spiced chicken curry served with crunchy beaten rice, roasted bhatmas, spiced aloo and tomato chutney.', '["Chicken Curry", "Beaten Rice Platter"]'::jsonb, 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80', 'Chicken Khaja Set', true),
('item-100', 'Buff Khaja Set', 'khaja-mains', 'Traditional Nepali', 310, 'Local Favorite', 'non-veg', 'Pan-fried spicy buff choila/curry paired with beaten rice, spiced potato pickle, crunchy bhatmas and fresh salad.', '["Spiced Buff Meat", "Authentic Flavors"]'::jsonb, 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80', 'Buff Khaja Set', true),
('item-101', 'Mix Khaja Set', 'khaja-mains', 'Grand Thali', 400, 'Special Combo', 'non-veg', 'The complete feast featuring spiced chicken, savory buff, boiled egg, beaten rice, aloo sadheko and assorted condiments.', '["Chicken + Buff + Egg", "Royal Feast"]'::jsonb, 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80', 'Mix Khaja Set', true),
('item-102', 'Buff Keema Noodles', 'khaja-mains', 'Keema Noodles', 280, 'Flavorful', 'non-veg', 'Steaming noodles generously smothered in rich, aromatic minced buff keema gravy cooked with garlic, ginger and herbs.', '["Minced Buff Sauce", "Wok Noodles"]'::jsonb, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80', 'Buff Keema Noodles', true),
('item-103', 'Chicken Keema Noodles', 'khaja-mains', 'Keema Noodles', 250, 'Popular', 'non-veg', 'Wok-tossed noodles crowned with seasoned minced chicken gravy, fresh chopped scallions and fragrant spices.', '["Chicken Keema", "Fresh Scallions"]'::jsonb, 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80', 'Chicken Keema Noodles', true),
('item-104', 'Mix Keema Noodles', 'khaja-mains', 'Keema Noodles', 350, 'House Special', 'non-veg', 'Signature noodle bowl topped with combined minced chicken and savory buff keema simmered in house masala.', '["Chicken & Buff", "Rich & Spicy"]'::jsonb, 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=600&q=80', 'Mix Keema Noodles', true),
('item-105', 'Chicken Thukpa', 'khaja-mains', 'Himalayan Noodle Soup', 220, 'Warm & Comforting', 'non-veg', 'Steaming aromatic Himalayan soup noodles with tender chicken strips, carrots, cabbage, and rich spiced broth.', '["Warm Broth", "Chicken Strips"]'::jsonb, 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&w=600&q=80', 'Chicken Thukpa', true),
('item-106', 'Buff Thukpa', 'khaja-mains', 'Himalayan Noodle Soup', 250, 'Hearty', 'non-veg', 'Slow-simmered mountain broth with noodles, savory buff slices, garlic, ginger and seasonal greens.', '["Buff Slices", "Spiced Soup"]'::jsonb, 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=600&q=80', 'Buff Thukpa', true),
('item-107', 'Egg Thukpa', 'khaja-mains', 'Himalayan Noodle Soup', 200, 'Vegetarian Option', 'veg', 'Wholesome hot noodle soup with fresh boiled eggs, garden veggies, and garlic-infused vegetable broth.', '["Farm Eggs", "Comforting Broth"]'::jsonb, 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?auto=format&fit=crop&w=600&q=80', 'Egg Thukpa', true),
('item-108', 'Veg Thukpa', 'khaja-mains', 'Himalayan Noodle Soup', 150, 'Pure Veg', 'veg', 'Gentle and soothing Himalayan vegetable noodle soup packed with fresh cabbage, carrots, onion and cilantro.', '["100% Vegetarian", "Garden Vegetables"]'::jsonb, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80', 'Veg Thukpa', true),
('item-109', 'Mix Thukpa', 'khaja-mains', 'Himalayan Noodle Soup', 300, 'Deluxe Soup', 'non-veg', 'Grand bowl loaded with chicken, buff, boiled egg, vegetables and hot flavored Himalayan soup broth.', '["Chicken, Buff & Egg", "King Size"]'::jsonb, 'https://images.unsplash.com/photo-1547928576-a4a33237cbc3?auto=format&fit=crop&w=600&q=80', 'Mix Thukpa', true),
('item-110', 'Veg Fry Rice', 'khaja-mains', 'Fried Rice', 200, 'Wok Fresh', 'veg', 'Fluffy basmati rice tossed in hot wok with sweet carrots, green peas, capsicum and soy seasoning.', '["Basmati Rice", "Fresh Vegetables"]'::jsonb, 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80', 'Veg Fry Rice', true),
('item-111', 'Chicken Fry Rice', 'khaja-mains', 'Fried Rice', 250, 'Popular', 'non-veg', 'Aromatic fried rice stir-fried with diced tender chicken, scallions, eggs, and cracked black pepper.', '["Tender Chicken", "Wok Stirred"]'::jsonb, 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=600&q=80', 'Chicken Fry Rice', true),
('item-112', 'Buff Fry Rice', 'khaja-mains', 'Fried Rice', 250, 'Spicy & Savory', 'non-veg', 'Smoky wok-tossed basmati rice with spiced shredded buff, soy sauce, and aromatic garlic butter.', '["Spiced Buff Pieces", "Fragrant Rice"]'::jsonb, 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80', 'Buff Fry Rice', true),
('item-113', 'Mix Fry Rice', 'khaja-mains', 'Fried Rice', 300, 'Chef Choice', 'non-veg', 'Ultimate fried rice combination with chicken, buff, egg, and crunchy garden vegetables in wok glaze.', '["Chicken, Buff & Egg", "Deluxe Basmati"]'::jsonb, 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80', 'Mix Fry Rice', true),
('item-114', 'Mustang Aalu', 'snacks-sides', 'Famous Mountain Snack', 250, 'Must Try', 'non-veg', 'Crispy fried potato wedges tossed in authentic Mustang jimbu herbs, roasted chili flakes and garlic butter.', '["Crispy Wedges", "Authentic Jimbu Herb"]'::jsonb, 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80', 'Mustang Aalu', true),
('item-115', 'Sukuti Sadheko', 'snacks-sides', 'Nepali Delicacy', 350, 'Authentic', 'non-veg', 'Smoky dried meat shredded and tossed with raw mustard oil, roasted garlic, green chili, onion and fresh lemon.', '["Smoky Dried Meat", "Spicy & Pungent"]'::jsonb, 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80', 'Sukuti Sadheko', true),
('item-116', 'Chicken Sadheko', 'snacks-sides', 'Nepali Sadheko', 300, 'Bestseller', 'non-veg', 'Seared spiced chicken marinated with fresh coriander, diced red onions, tomatoes, green chilies and lime.', '["Spiced Chicken", "Fresh Lime & Coriander"]'::jsonb, 'https://images.unsplash.com/photo-1606471191009-63994c53433b?auto=format&fit=crop&w=600&q=80', 'Chicken Sadheko', true),
('item-117', 'Buff Sadheko', 'snacks-sides', 'Nepali Sadheko', 280, 'Spicy', 'non-veg', 'Tender spiced buff cubes marinated in roasted fenugreek, garlic ginger paste, mustard oil and fresh herbs.', '["Tender Buff Cubes", "Roasted Fenugreek"]'::jsonb, 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80', 'Buff Sadheko', true),
('item-118', 'Bhatmas Sadheko', 'snacks-sides', 'Crispy Snack', 120, 'Classic', 'non-veg', 'Deep roasted crunchy soybeans mixed with raw mustard oil, finely chopped onions, chilies and lemon juice.', '["Roasted Soybeans", "High Protein Crunch"]'::jsonb, 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=600&q=80', 'Bhatmas Sadheko', true),
('item-119', 'Peanut Sadheko', 'snacks-sides', 'Crispy Snack', 130, 'Addictive', 'non-veg', 'Roasted crunchy peanuts tossed with diced tomatoes, onions, cilantro, green chilies, and tangy chaat masala.', '["Roasted Peanuts", "Tangy Chaat Masala"]'::jsonb, 'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?auto=format&fit=crop&w=600&q=80', 'Peanut Sadheko', true),
('item-120', 'Wai-Wai Sadheko (2 Packets)', 'snacks-sides', 'Nepali Street Food', 100, 'Comfort Food', 'non-veg', 'Two packets of crunchy crushed Wai-Wai noodles tossed with onions, tomatoes, green chilies, seasoning & lime.', '["2x Wai-Wai Noodles", "Nostalgic Taste"]'::jsonb, 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=600&q=80', 'Wai-Wai Sadheko (2 Packets)', true),
('item-121', 'Aalu Sadheko', 'snacks-sides', 'Potato Salad', 140, 'Traditional', 'non-veg', 'Tender boiled potatoes spiced with roasted fenugreek oil, turmeric, green chilies, cilantro and lemon juice.', '["Spiced Potatoes", "Roasted Fenugreek"]'::jsonb, 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80', 'Aalu Sadheko', true),
('item-122', 'French Fries', 'snacks-sides', 'Crispy Fries', 170, 'Crispy', 'non-veg', 'Golden, crispy hand-cut potatoes fried to perfection, lightly salted and served with creamy dip.', '["Golden Crispy", "Sea Salted"]'::jsonb, 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80', 'French Fries', true),
('item-123', 'Peri-Peri Fries', 'snacks-sides', 'Spiced Fries', 190, 'Spicy', 'non-veg', 'Hot crispy potato fries dusted generously with zesty, tangy and fiery African peri-peri spice mix.', '["Peri-Peri Dust", "Zesty Kick"]'::jsonb, 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?auto=format&fit=crop&w=600&q=80', 'Peri-Peri Fries', true),
('item-124', 'Cheese Ball', 'snacks-sides', 'Deep Fried', 310, 'Cheesy Delight', 'non-veg', 'Crispy golden breaded spheres that melt in your mouth with an oozy, savory melted cheese center.', '["Molten Cheese Center", "Golden Crust"]'::jsonb, 'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=600&q=80', 'Cheese Ball', true),
('item-125', 'Fish Finger', 'snacks-sides', 'Seafood', 350, 'Crispy Fish', 'non-veg', 'Fresh fish fillets cut into batons, herb-marinated, rolled in crunchy breadcrumbs and fried golden.', '["Tender Fish Fillet", "Tartar Dip"]'::jsonb, 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80', 'Fish Finger', true),
('item-126', 'Chicken Kabab (Pahadi Best)', 'snacks-sides', 'Himalayan Grill', 350, 'House Special', 'non-veg', 'Chef signature mountain-spiced succulent chicken kababs grilled over hot embers with garlic mint chutney.', '["Pahadi Spices", "Charcoal Grilled"]'::jsonb, 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=600&q=80', 'Chicken Kabab (Pahadi Best)', true),
('item-127', 'Veg Pakouda', 'snacks-sides', 'Crispy Fritters', 200, 'Tea Time Fav', 'veg', 'Crispy chickpea-flour fritters with finely sliced onions, seasonal vegetables, green chili and cumin.', '["Gram Flour Crunch", "Perfect With Coffee"]'::jsonb, 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80', 'Veg Pakouda', true),
('item-128', 'Sausages (2 Pieces)', 'snacks-sides', 'Quick Bite', 120, 'Quick Snack', 'non-veg', 'Two grilled savory sausages served hot with our house spicy tomato and mustard dipping sauces.', '["2 Pieces Grilled", "Spicy Dips"]'::jsonb, 'https://images.unsplash.com/photo-1585325701165-351af916e581?auto=format&fit=crop&w=600&q=80', 'Sausages (2 Pieces)', true),
('item-129', 'Sausage Sadheko', 'snacks-sides', 'Nepali Sadheko', 160, 'Spicy Bite', 'non-veg', 'Sliced grilled sausages tossed with red onions, tomatoes, fresh cilantro, fiery green chilies and lemon.', '["Sliced Sausages", "Pungent Mustard Dressing"]'::jsonb, 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80', 'Sausage Sadheko', true),
('item-130', 'Aalu Stick', 'snacks-sides', 'Crispy Potato', 160, 'Crunchy', 'non-veg', 'Seasoned potato sticks deep-fried to a golden crunch, dusted with savory mountain spice seasoning.', '["Potato Sticks", "Spice Dusted"]'::jsonb, 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80', 'Aalu Stick', true),
('item-131', 'Chicken Chilly', 'snacks-sides', 'Indo-Chinese Chilly', 280, 'Spicy Favorite', 'non-veg', 'Wok-tossed chicken chunks stir-fried in a fiery dark soy chili sauce with bell peppers and crunchy onions.', '["Boneless Chicken", "Wok Tossed"]'::jsonb, 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80', 'Chicken Chilly', true),
('item-132', 'Buff Chilly', 'snacks-sides', 'Indo-Chinese Chilly', 310, 'Hot & Spicy', 'non-veg', 'Crispy seasoned buff meat stir-fried with hot green chilies, garlic, capsicum, and thick spicy gravy.', '["Crispy Buff", "Fiery Green Chilies"]'::jsonb, 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80', 'Buff Chilly', true),
('item-133', 'Sausage Chilly', 'snacks-sides', 'Indo-Chinese Chilly', 250, 'Tangy Spicy', 'non-veg', 'Sliced savory sausages tossed in hot wok with onions, green peppers, soy sauce and sweet chili glaze.', '["Sliced Sausages", "Sweet & Spicy"]'::jsonb, 'https://images.unsplash.com/photo-1585325701165-351af916e581?auto=format&fit=crop&w=600&q=80', 'Sausage Chilly', true),
('item-134', 'Chips Chilly', 'snacks-sides', 'Indo-Chinese Chilly', 230, 'Crispy Snack', 'non-veg', 'Crispy potato chips tossed with garlic, ginger, chopped chilies, onions, and spicy Indo-Chinese sauce.', '["Crispy Chips", "Spicy Garlic Glaze"]'::jsonb, 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=600&q=80', 'Chips Chilly', true),
('item-135', 'Nan Chicken Kima', 'snacks-sides', 'Stuffed Naan', 250, 'Stuffed Bread', 'non-veg', 'Oven-baked flatbread stuffed generously with spiced minced chicken, fresh herbs, and coriander butter.', '["Chicken Keema Stuffed", "Oven Baked"]'::jsonb, 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80', 'Nan Chicken Kima', true),
('item-136', 'Cheese Nan', 'snacks-sides', 'Naan Bread', 120, 'Cheesy', 'non-veg', 'Fresh clay-oven flatbread stuffed with savory melted mozzarella cheese and brushed with melted butter.', '["Mozzarella Stuffed", "Butter Glazed"]'::jsonb, 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80', 'Cheese Nan', true),
('item-137', 'Garlic Nan', 'snacks-sides', 'Naan Bread', 140, 'Aromatic', 'non-veg', 'Soft tandoori flatbread studded with roasted minced garlic, fresh coriander leaves and melted butter.', '["Roasted Garlic", "Herb Butter"]'::jsonb, 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80', 'Garlic Nan', true),
('item-138', 'Butter Nan', 'snacks-sides', 'Naan Bread', 100, 'Classic', 'non-veg', 'Traditional pillowy soft clay-oven baked naan brushed with golden creamy alpine butter.', '["Pure Butter", "Soft & Fluffy"]'::jsonb, 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80', 'Butter Nan', true),
('item-139', 'Fruit Salad', 'snacks-sides', 'Fresh Salad', 190, 'Fresh & Healthy', 'non-veg', 'Bowl of seasonal mountain fruits, freshly diced and dressed with light citrus honey glaze.', '["Seasonal Fruits", "Natural Honey Touch"]'::jsonb, 'https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&w=600&q=80', 'Fruit Salad', true),
('item-140', 'Green Salad', 'snacks-sides', 'Fresh Salad', 150, 'Crisp', 'non-veg', 'Crisp farm cucumbers, ripe tomatoes, carrots, sliced red onion, and green chilies served with lemon wedges.', '["Fresh Cucumbers & Tomatoes", "Lemon Dressing"]'::jsonb, 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80', 'Green Salad', true),
('item-141', 'Salad Sadheko', 'snacks-sides', 'Nepali Salad', 120, 'Spicy Salad', 'non-veg', 'Fresh sliced garden vegetables marinated in mustard oil, roasted fenugreek, green chili and lemon.', '["Fresh Garden Veggies", "Sadheko Dressing"]'::jsonb, 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80', 'Salad Sadheko', true),
('item-142', 'Hukka (Classic Flavor)', 'bar-lounge', 'Lounge Hukka', 400, 'Lounge Ritual', 'non-veg', 'Premium coal-heated hookah pipe prepared in your favorite fruity or mint herbal flavor.', '["Smooth Smoke", "Choice of Flavor"]'::jsonb, 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=600&q=80', 'Hukka (Classic Flavor)', true),
('item-143', 'Garnished Hukka', 'bar-lounge', 'Lounge Hukka', 450, 'Deluxe Special', 'non-veg', 'Deluxe garnished hookah setup with chilled fruit base, fresh mint infusion, and dense cooling vapor.', '["Fruit Ice Base", "Long Lasting"]'::jsonb, 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=600&q=80', 'Garnished Hukka', true),
('item-144', 'Budweiser Beer (650ml)', 'bar-lounge', 'Chilled Beer', 600, 'Imported Brand', 'non-veg', 'The King of Beers: crisp, clean American lager brewed with the finest barley malt and rice.', '["650ml Bottle", "Ice Chilled"]'::jsonb, 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=600&q=80', 'Budweiser Beer (650ml)', true),
('item-145', 'Carlsberg Beer (650ml)', 'bar-lounge', 'Chilled Beer', 580, 'Danish Pilsner', 'non-veg', 'Probably the best beer in the world: crisp, refreshing Danish pilsner with well-balanced bitterness.', '["650ml Bottle", "Danish Malt"]'::jsonb, 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?auto=format&fit=crop&w=600&q=80', 'Carlsberg Beer (650ml)', true),
('item-146', 'Tuborg Classic (650ml)', 'bar-lounge', 'Chilled Beer', 550, 'Local Favorite', 'non-veg', 'Crisp and bottom-fermented lager with mild bitterness and rich floral hop aroma.', '["650ml Bottle", "Hop Aroma"]'::jsonb, 'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?auto=format&fit=crop&w=600&q=80', 'Tuborg Classic (650ml)', true),
('item-147', 'Gorkha Strong (650ml)', 'bar-lounge', 'Chilled Beer', 500, 'Nepali Brew', 'non-veg', 'Brewed with pure Himalayan water: bold, robust malt character and smooth finish.', '["650ml Bottle", "Himalayan Water"]'::jsonb, 'https://images.unsplash.com/photo-1584225065152-4a1454aa3d4e?auto=format&fit=crop&w=600&q=80', 'Gorkha Strong (650ml)', true),
('item-148', 'Barahsinghe Craft Beer (650ml)', 'bar-lounge', 'Chilled Beer', 580, 'Craft Brew', 'non-veg', 'Nepal premier craft pilsner brewed with imported noble hops and pure spring water.', '["650ml Bottle", "Craft Pilsner"]'::jsonb, 'https://images.unsplash.com/photo-1567696911980-2eed69a46042?auto=format&fit=crop&w=600&q=80', 'Barahsinghe Craft Beer (650ml)', true),
('item-149', 'Apple Cider', 'bar-lounge', 'Sparkling Cider', 250, 'Crisp & Sweet', 'non-veg', 'Crisp fermented sparkling apple cider offering a refreshing fruit-forward effervescence.', '["Fermented Apple", "Bubbly"]'::jsonb, 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80', 'Apple Cider', true),
('item-150', 'Margarita Cocktail', 'bar-lounge', 'Cocktail', 450, 'Signature Cocktail', 'non-veg', 'Classic cocktail shaken with silver tequila, triple sec, and fresh lime juice, served with salted rim.', '["Silver Tequila", "Salted Rim"]'::jsonb, 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', 'Margarita Cocktail', true),
('item-151', 'Special Hot Punch Rum', 'bar-lounge', 'Winter Warmer', 400, 'Winter Special', 'non-veg', 'Traditional warming winter punch with spiced Khukri rum, cloves, cinnamon stick, honey and citrus peel.', '["Spiced Rum", "Hot Spiced Punch"]'::jsonb, 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80', 'Special Hot Punch Rum', true),
('item-152', 'Hot Punch Rum', 'bar-lounge', 'Winter Warmer', 320, 'Warm Spirit', 'non-veg', 'Warm dark rum mixed with spiced mountain water, lemon juice, and honey warmth.', '["Dark Rum", "Lemon & Honey"]'::jsonb, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80', 'Hot Punch Rum', true),
('item-153', 'Old Durbar (Black Chimney)', 'bar-lounge', 'Himalayan Whisky', 350, 'Peg 30ml / Rs. 600 (60ml)', 'non-veg', 'Smoky reserve blended malt scotch and grain spirits finished in charred oak barrels. Bottle: Rs. 4500 (Full), Rs. 2300 (Half).', '["30ml: Rs. 350", "60ml: Rs. 600", "Full: Rs. 4500"]'::jsonb, 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80', 'Old Durbar (Black Chimney)', true),
('item-154', 'Old Durbar (Red)', 'bar-lounge', 'Himalayan Whisky', 350, 'Peg 30ml / Rs. 550 (60ml)', 'non-veg', 'Smooth blended whisky crafted with English malt and purified mountain spring water. Bottle: Rs. 3200 (Full), Rs. 1950 (Half).', '["30ml: Rs. 350", "60ml: Rs. 550", "Full: Rs. 3200"]'::jsonb, 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80', 'Old Durbar (Red)', true),
('item-155', 'Johnnie Walker Red Label', 'bar-lounge', 'Scotch Whisky', 450, 'Peg 30ml / Rs. 840 (60ml)', 'non-veg', 'World-famous Scotch whisky blending light whiskies from Scotland east coast with dark peaty whiskies. Full Bottle: Rs. 7500.', '["30ml: Rs. 450", "60ml: Rs. 840", "Full: Rs. 7500"]'::jsonb, 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?auto=format&fit=crop&w=600&q=80', 'Johnnie Walker Red Label', true),
('item-156', 'Khukri Rum (Rumm Khukuri)', 'bar-lounge', 'Himalayan Dark Rum', 350, 'Peg 30ml / Rs. 520 (60ml)', 'non-veg', 'Grand Himalayan dark rum distilled since 1959 with rich treacle, dark honey and caramel aromas. Full Bottle: Rs. 3100.', '["30ml: Rs. 350", "60ml: Rs. 520", "Full: Rs. 3100"]'::jsonb, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80', 'Khukri Rum (Rumm Khukuri)', true),
('item-157', 'Old Monk Rum', 'bar-lounge', 'Dark Rum', 360, 'Peg 30ml / Rs. 530 (60ml)', 'non-veg', 'Iconic vatted 7-year aged dark rum with unmistakable notes of molasses, oak wood, and sweet vanilla. Full Bottle: Rs. 3130.', '["30ml: Rs. 360", "60ml: Rs. 530", "Full: Rs. 3130"]'::jsonb, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80', 'Old Monk Rum', true),
('item-158', '8848 Vodka', 'bar-lounge', 'Himalayan Vodka', 300, 'Peg 30ml / Rs. 600 (90ml)', 'non-veg', 'Distilled 5 times with French grain and blended with pure glacial spring water of Mt. Everest. Full Bottle: Rs. 3500.', '["30ml: Rs. 300", "90ml: Rs. 600", "Full: Rs. 3500"]'::jsonb, 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', '8848 Vodka', true),
('item-159', 'Absolut Vodka', 'bar-lounge', 'Swedish Vodka', 500, 'Peg 30ml / Rs. 1000 (90ml)', 'non-veg', 'World famous Swedish winter wheat vodka distilled continuously for legendary purity. Full Bottle: Rs. 8000.', '["30ml: Rs. 500", "90ml: Rs. 1000", "Full: Rs. 8000"]'::jsonb, 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', 'Absolut Vodka', true),
('item-160', 'Smirnoff Vodka', 'bar-lounge', 'Classic Vodka', 300, 'Peg 30ml / Rs. 600 (90ml)', 'non-veg', 'Triple-distilled and 10-times charcoal filtered for iconic smoothness and crisp dry taste. Full Bottle: Rs. 3500.', '["30ml: Rs. 300", "90ml: Rs. 600", "Full: Rs. 3500"]'::jsonb, 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80', 'Smirnoff Vodka', true),
('item-161', 'Robertson Winery Bottle', 'bar-lounge', 'Fine Wine', 2600, 'Full Bottle', 'non-veg', 'South African premium estate bottled wine boasting smooth ruby fruit notes and balanced finish.', '["Full Bottle", "South African Vintage"]'::jsonb, 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80', 'Robertson Winery Bottle', true),
('item-162', 'King Hills Wine Bottle', 'bar-lounge', 'Local Vintage', 1500, 'Full Bottle', 'non-veg', 'Sweet and fruit-forward mountain vintage red wine crafted locally in Nepal.', '["Full Bottle", "Local Favorite"]'::jsonb, 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=600&q=80', 'King Hills Wine Bottle', true),
('item-163', 'J.P. Chenet Wine Bottle', 'bar-lounge', 'French Wine', 3500, 'French Classic', 'non-veg', 'Authentic French wine bottled in its distinctive curved neck bottle with luscious berry bouquet.', '["Full Bottle", "Product of France"]'::jsonb, 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=600&q=80', 'J.P. Chenet Wine Bottle', true)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    sub_category = EXCLUDED.sub_category,
    price = EXCLUDED.price,
    tag = EXCLUDED.tag,
    dietary = EXCLUDED.dietary,
    description = EXCLUDED.description,
    details = EXCLUDED.details,
    image = EXCLUDED.image,
    alt = EXCLUDED.alt,
    is_available = EXCLUDED.is_available;
